# Generated by Django 6.0.6 on 2026-06-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RipenessGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('brown', 'Brown'), ('overripe', 'Overripe')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('best_uses', models.TextField()),
                ('cooking_tips', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ripeness_guide/')),
            ],
            options={
                'ordering': ['stage'],
            },
        ),
    ]
