# Generated by Django 6.0.6 on 2026-06-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantain_ripeness_guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ripenessguide',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='ripenessguide',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
